//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DistributedServices.Cobranzas_Bancarias_API_Davivienda_ServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Saldos", Namespace="http://Cobranzas_Bancarias_API_Davivienda/")]
    [System.SerializableAttribute()]
    public partial class Saldos : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private DistributedServices.Cobranzas_Bancarias_API_Davivienda_ServiceReference.Error ErrorField;
        
        private DistributedServices.Cobranzas_Bancarias_API_Davivienda_ServiceReference.Familia FamiliaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private DistributedServices.Cobranzas_Bancarias_API_Davivienda_ServiceReference.Saldo[] SaldosMemberField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public DistributedServices.Cobranzas_Bancarias_API_Davivienda_ServiceReference.Error Error {
            get {
                return this.ErrorField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorField, value) != true)) {
                    this.ErrorField = value;
                    this.RaisePropertyChanged("Error");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public DistributedServices.Cobranzas_Bancarias_API_Davivienda_ServiceReference.Familia Familia {
            get {
                return this.FamiliaField;
            }
            set {
                if ((object.ReferenceEquals(this.FamiliaField, value) != true)) {
                    this.FamiliaField = value;
                    this.RaisePropertyChanged("Familia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="Saldos", EmitDefaultValue=false)]
        public DistributedServices.Cobranzas_Bancarias_API_Davivienda_ServiceReference.Saldo[] SaldosMember {
            get {
                return this.SaldosMemberField;
            }
            set {
                if ((object.ReferenceEquals(this.SaldosMemberField, value) != true)) {
                    this.SaldosMemberField = value;
                    this.RaisePropertyChanged("SaldosMember");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Error", Namespace="http://Cobranzas_Bancarias_API_Davivienda/")]
    [System.SerializableAttribute()]
    public partial class Error : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MensajeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Codigo {
            get {
                return this.CodigoField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoField, value) != true)) {
                    this.CodigoField = value;
                    this.RaisePropertyChanged("Codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Mensaje {
            get {
                return this.MensajeField;
            }
            set {
                if ((object.ReferenceEquals(this.MensajeField, value) != true)) {
                    this.MensajeField = value;
                    this.RaisePropertyChanged("Mensaje");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Familia", Namespace="http://Cobranzas_Bancarias_API_Davivienda/")]
    [System.SerializableAttribute()]
    public partial class Familia : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NucleoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Nucleo {
            get {
                return this.NucleoField;
            }
            set {
                if ((object.ReferenceEquals(this.NucleoField, value) != true)) {
                    this.NucleoField = value;
                    this.RaisePropertyChanged("Nucleo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Saldo", Namespace="http://Cobranzas_Bancarias_API_Davivienda/")]
    [System.SerializableAttribute()]
    public partial class Saldo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TipoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ConceptoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumFacturaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CuotaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ValorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MonedaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VenceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PeriodoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Tipo {
            get {
                return this.TipoField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoField, value) != true)) {
                    this.TipoField = value;
                    this.RaisePropertyChanged("Tipo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Concepto {
            get {
                return this.ConceptoField;
            }
            set {
                if ((object.ReferenceEquals(this.ConceptoField, value) != true)) {
                    this.ConceptoField = value;
                    this.RaisePropertyChanged("Concepto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string NumFactura {
            get {
                return this.NumFacturaField;
            }
            set {
                if ((object.ReferenceEquals(this.NumFacturaField, value) != true)) {
                    this.NumFacturaField = value;
                    this.RaisePropertyChanged("NumFactura");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Cuota {
            get {
                return this.CuotaField;
            }
            set {
                if ((object.ReferenceEquals(this.CuotaField, value) != true)) {
                    this.CuotaField = value;
                    this.RaisePropertyChanged("Cuota");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Valor {
            get {
                return this.ValorField;
            }
            set {
                if ((object.ReferenceEquals(this.ValorField, value) != true)) {
                    this.ValorField = value;
                    this.RaisePropertyChanged("Valor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Moneda {
            get {
                return this.MonedaField;
            }
            set {
                if ((object.ReferenceEquals(this.MonedaField, value) != true)) {
                    this.MonedaField = value;
                    this.RaisePropertyChanged("Moneda");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string Vence {
            get {
                return this.VenceField;
            }
            set {
                if ((object.ReferenceEquals(this.VenceField, value) != true)) {
                    this.VenceField = value;
                    this.RaisePropertyChanged("Vence");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string Periodo {
            get {
                return this.PeriodoField;
            }
            set {
                if ((object.ReferenceEquals(this.PeriodoField, value) != true)) {
                    this.PeriodoField = value;
                    this.RaisePropertyChanged("Periodo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://Cobranzas_Bancarias_API_Davivienda/", ConfigurationName="Cobranzas_Bancarias_API_Davivienda_ServiceReference.Cobranzas_Bancarias_API_Daviv" +
        "iendaSoap")]
    public interface Cobranzas_Bancarias_API_DaviviendaSoap {
        
        // CODEGEN: Generating message contract since element name sBank from namespace http://Cobranzas_Bancarias_API_Davivienda/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://Cobranzas_Bancarias_API_Davivienda/ConsultaSaldo", ReplyAction="*")]
        DistributedServices.Cobranzas_Bancarias_API_Davivienda_ServiceReference.ConsultaSaldoResponse ConsultaSaldo(DistributedServices.Cobranzas_Bancarias_API_Davivienda_ServiceReference.ConsultaSaldoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Cobranzas_Bancarias_API_Davivienda/ConsultaSaldo", ReplyAction="*")]
        System.Threading.Tasks.Task<DistributedServices.Cobranzas_Bancarias_API_Davivienda_ServiceReference.ConsultaSaldoResponse> ConsultaSaldoAsync(DistributedServices.Cobranzas_Bancarias_API_Davivienda_ServiceReference.ConsultaSaldoRequest request);
        
        // CODEGEN: Generating message contract since element name sBank from namespace http://Cobranzas_Bancarias_API_Davivienda/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://Cobranzas_Bancarias_API_Davivienda/PagoCuota", ReplyAction="*")]
        DistributedServices.Cobranzas_Bancarias_API_Davivienda_ServiceReference.PagoCuotaResponse PagoCuota(DistributedServices.Cobranzas_Bancarias_API_Davivienda_ServiceReference.PagoCuotaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Cobranzas_Bancarias_API_Davivienda/PagoCuota", ReplyAction="*")]
        System.Threading.Tasks.Task<DistributedServices.Cobranzas_Bancarias_API_Davivienda_ServiceReference.PagoCuotaResponse> PagoCuotaAsync(DistributedServices.Cobranzas_Bancarias_API_Davivienda_ServiceReference.PagoCuotaRequest request);
        
        // CODEGEN: Generating message contract since element name sBank from namespace http://Cobranzas_Bancarias_API_Davivienda/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://Cobranzas_Bancarias_API_Davivienda/ReversarPago", ReplyAction="*")]
        DistributedServices.Cobranzas_Bancarias_API_Davivienda_ServiceReference.ReversarPagoResponse ReversarPago(DistributedServices.Cobranzas_Bancarias_API_Davivienda_ServiceReference.ReversarPagoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Cobranzas_Bancarias_API_Davivienda/ReversarPago", ReplyAction="*")]
        System.Threading.Tasks.Task<DistributedServices.Cobranzas_Bancarias_API_Davivienda_ServiceReference.ReversarPagoResponse> ReversarPagoAsync(DistributedServices.Cobranzas_Bancarias_API_Davivienda_ServiceReference.ReversarPagoRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConsultaSaldoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConsultaSaldo", Namespace="http://Cobranzas_Bancarias_API_Davivienda/", Order=0)]
        public DistributedServices.Cobranzas_Bancarias_API_Davivienda_ServiceReference.ConsultaSaldoRequestBody Body;
        
        public ConsultaSaldoRequest() {
        }
        
        public ConsultaSaldoRequest(DistributedServices.Cobranzas_Bancarias_API_Davivienda_ServiceReference.ConsultaSaldoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Cobranzas_Bancarias_API_Davivienda/")]
    public partial class ConsultaSaldoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sBank;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string sPass;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string sCodigo;
        
        public ConsultaSaldoRequestBody() {
        }
        
        public ConsultaSaldoRequestBody(string sBank, string sPass, string sCodigo) {
            this.sBank = sBank;
            this.sPass = sPass;
            this.sCodigo = sCodigo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConsultaSaldoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConsultaSaldoResponse", Namespace="http://Cobranzas_Bancarias_API_Davivienda/", Order=0)]
        public DistributedServices.Cobranzas_Bancarias_API_Davivienda_ServiceReference.ConsultaSaldoResponseBody Body;
        
        public ConsultaSaldoResponse() {
        }
        
        public ConsultaSaldoResponse(DistributedServices.Cobranzas_Bancarias_API_Davivienda_ServiceReference.ConsultaSaldoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Cobranzas_Bancarias_API_Davivienda/")]
    public partial class ConsultaSaldoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public DistributedServices.Cobranzas_Bancarias_API_Davivienda_ServiceReference.Saldos ConsultaSaldoResult;
        
        public ConsultaSaldoResponseBody() {
        }
        
        public ConsultaSaldoResponseBody(DistributedServices.Cobranzas_Bancarias_API_Davivienda_ServiceReference.Saldos ConsultaSaldoResult) {
            this.ConsultaSaldoResult = ConsultaSaldoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PagoCuotaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PagoCuota", Namespace="http://Cobranzas_Bancarias_API_Davivienda/", Order=0)]
        public DistributedServices.Cobranzas_Bancarias_API_Davivienda_ServiceReference.PagoCuotaRequestBody Body;
        
        public PagoCuotaRequest() {
        }
        
        public PagoCuotaRequest(DistributedServices.Cobranzas_Bancarias_API_Davivienda_ServiceReference.PagoCuotaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Cobranzas_Bancarias_API_Davivienda/")]
    public partial class PagoCuotaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sBank;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string sPass;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string @__oPago;
        
        public PagoCuotaRequestBody() {
        }
        
        public PagoCuotaRequestBody(string sBank, string sPass, string @__oPago) {
            this.sBank = sBank;
            this.sPass = sPass;
            this.@__oPago = @__oPago;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PagoCuotaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PagoCuotaResponse", Namespace="http://Cobranzas_Bancarias_API_Davivienda/", Order=0)]
        public DistributedServices.Cobranzas_Bancarias_API_Davivienda_ServiceReference.PagoCuotaResponseBody Body;
        
        public PagoCuotaResponse() {
        }
        
        public PagoCuotaResponse(DistributedServices.Cobranzas_Bancarias_API_Davivienda_ServiceReference.PagoCuotaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Cobranzas_Bancarias_API_Davivienda/")]
    public partial class PagoCuotaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public DistributedServices.Cobranzas_Bancarias_API_Davivienda_ServiceReference.Saldos PagoCuotaResult;
        
        public PagoCuotaResponseBody() {
        }
        
        public PagoCuotaResponseBody(DistributedServices.Cobranzas_Bancarias_API_Davivienda_ServiceReference.Saldos PagoCuotaResult) {
            this.PagoCuotaResult = PagoCuotaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ReversarPagoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ReversarPago", Namespace="http://Cobranzas_Bancarias_API_Davivienda/", Order=0)]
        public DistributedServices.Cobranzas_Bancarias_API_Davivienda_ServiceReference.ReversarPagoRequestBody Body;
        
        public ReversarPagoRequest() {
        }
        
        public ReversarPagoRequest(DistributedServices.Cobranzas_Bancarias_API_Davivienda_ServiceReference.ReversarPagoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Cobranzas_Bancarias_API_Davivienda/")]
    public partial class ReversarPagoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sBank;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string sPass;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string @__oPago;
        
        public ReversarPagoRequestBody() {
        }
        
        public ReversarPagoRequestBody(string sBank, string sPass, string @__oPago) {
            this.sBank = sBank;
            this.sPass = sPass;
            this.@__oPago = @__oPago;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ReversarPagoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ReversarPagoResponse", Namespace="http://Cobranzas_Bancarias_API_Davivienda/", Order=0)]
        public DistributedServices.Cobranzas_Bancarias_API_Davivienda_ServiceReference.ReversarPagoResponseBody Body;
        
        public ReversarPagoResponse() {
        }
        
        public ReversarPagoResponse(DistributedServices.Cobranzas_Bancarias_API_Davivienda_ServiceReference.ReversarPagoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Cobranzas_Bancarias_API_Davivienda/")]
    public partial class ReversarPagoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public DistributedServices.Cobranzas_Bancarias_API_Davivienda_ServiceReference.Saldos ReversarPagoResult;
        
        public ReversarPagoResponseBody() {
        }
        
        public ReversarPagoResponseBody(DistributedServices.Cobranzas_Bancarias_API_Davivienda_ServiceReference.Saldos ReversarPagoResult) {
            this.ReversarPagoResult = ReversarPagoResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface Cobranzas_Bancarias_API_DaviviendaSoapChannel : DistributedServices.Cobranzas_Bancarias_API_Davivienda_ServiceReference.Cobranzas_Bancarias_API_DaviviendaSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Cobranzas_Bancarias_API_DaviviendaSoapClient : System.ServiceModel.ClientBase<DistributedServices.Cobranzas_Bancarias_API_Davivienda_ServiceReference.Cobranzas_Bancarias_API_DaviviendaSoap>, DistributedServices.Cobranzas_Bancarias_API_Davivienda_ServiceReference.Cobranzas_Bancarias_API_DaviviendaSoap {
        
        public Cobranzas_Bancarias_API_DaviviendaSoapClient() {
        }
        
        public Cobranzas_Bancarias_API_DaviviendaSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Cobranzas_Bancarias_API_DaviviendaSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Cobranzas_Bancarias_API_DaviviendaSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Cobranzas_Bancarias_API_DaviviendaSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DistributedServices.Cobranzas_Bancarias_API_Davivienda_ServiceReference.ConsultaSaldoResponse DistributedServices.Cobranzas_Bancarias_API_Davivienda_ServiceReference.Cobranzas_Bancarias_API_DaviviendaSoap.ConsultaSaldo(DistributedServices.Cobranzas_Bancarias_API_Davivienda_ServiceReference.ConsultaSaldoRequest request) {
            return base.Channel.ConsultaSaldo(request);
        }
        
        public DistributedServices.Cobranzas_Bancarias_API_Davivienda_ServiceReference.Saldos ConsultaSaldo(string sBank, string sPass, string sCodigo) {
            DistributedServices.Cobranzas_Bancarias_API_Davivienda_ServiceReference.ConsultaSaldoRequest inValue = new DistributedServices.Cobranzas_Bancarias_API_Davivienda_ServiceReference.ConsultaSaldoRequest();
            inValue.Body = new DistributedServices.Cobranzas_Bancarias_API_Davivienda_ServiceReference.ConsultaSaldoRequestBody();
            inValue.Body.sBank = sBank;
            inValue.Body.sPass = sPass;
            inValue.Body.sCodigo = sCodigo;
            DistributedServices.Cobranzas_Bancarias_API_Davivienda_ServiceReference.ConsultaSaldoResponse retVal = ((DistributedServices.Cobranzas_Bancarias_API_Davivienda_ServiceReference.Cobranzas_Bancarias_API_DaviviendaSoap)(this)).ConsultaSaldo(inValue);
            return retVal.Body.ConsultaSaldoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DistributedServices.Cobranzas_Bancarias_API_Davivienda_ServiceReference.ConsultaSaldoResponse> DistributedServices.Cobranzas_Bancarias_API_Davivienda_ServiceReference.Cobranzas_Bancarias_API_DaviviendaSoap.ConsultaSaldoAsync(DistributedServices.Cobranzas_Bancarias_API_Davivienda_ServiceReference.ConsultaSaldoRequest request) {
            return base.Channel.ConsultaSaldoAsync(request);
        }
        
        public System.Threading.Tasks.Task<DistributedServices.Cobranzas_Bancarias_API_Davivienda_ServiceReference.ConsultaSaldoResponse> ConsultaSaldoAsync(string sBank, string sPass, string sCodigo) {
            DistributedServices.Cobranzas_Bancarias_API_Davivienda_ServiceReference.ConsultaSaldoRequest inValue = new DistributedServices.Cobranzas_Bancarias_API_Davivienda_ServiceReference.ConsultaSaldoRequest();
            inValue.Body = new DistributedServices.Cobranzas_Bancarias_API_Davivienda_ServiceReference.ConsultaSaldoRequestBody();
            inValue.Body.sBank = sBank;
            inValue.Body.sPass = sPass;
            inValue.Body.sCodigo = sCodigo;
            return ((DistributedServices.Cobranzas_Bancarias_API_Davivienda_ServiceReference.Cobranzas_Bancarias_API_DaviviendaSoap)(this)).ConsultaSaldoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DistributedServices.Cobranzas_Bancarias_API_Davivienda_ServiceReference.PagoCuotaResponse DistributedServices.Cobranzas_Bancarias_API_Davivienda_ServiceReference.Cobranzas_Bancarias_API_DaviviendaSoap.PagoCuota(DistributedServices.Cobranzas_Bancarias_API_Davivienda_ServiceReference.PagoCuotaRequest request) {
            return base.Channel.PagoCuota(request);
        }
        
        public DistributedServices.Cobranzas_Bancarias_API_Davivienda_ServiceReference.Saldos PagoCuota(string sBank, string sPass, string @__oPago) {
            DistributedServices.Cobranzas_Bancarias_API_Davivienda_ServiceReference.PagoCuotaRequest inValue = new DistributedServices.Cobranzas_Bancarias_API_Davivienda_ServiceReference.PagoCuotaRequest();
            inValue.Body = new DistributedServices.Cobranzas_Bancarias_API_Davivienda_ServiceReference.PagoCuotaRequestBody();
            inValue.Body.sBank = sBank;
            inValue.Body.sPass = sPass;
            inValue.Body.@__oPago = @__oPago;
            DistributedServices.Cobranzas_Bancarias_API_Davivienda_ServiceReference.PagoCuotaResponse retVal = ((DistributedServices.Cobranzas_Bancarias_API_Davivienda_ServiceReference.Cobranzas_Bancarias_API_DaviviendaSoap)(this)).PagoCuota(inValue);
            return retVal.Body.PagoCuotaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DistributedServices.Cobranzas_Bancarias_API_Davivienda_ServiceReference.PagoCuotaResponse> DistributedServices.Cobranzas_Bancarias_API_Davivienda_ServiceReference.Cobranzas_Bancarias_API_DaviviendaSoap.PagoCuotaAsync(DistributedServices.Cobranzas_Bancarias_API_Davivienda_ServiceReference.PagoCuotaRequest request) {
            return base.Channel.PagoCuotaAsync(request);
        }
        
        public System.Threading.Tasks.Task<DistributedServices.Cobranzas_Bancarias_API_Davivienda_ServiceReference.PagoCuotaResponse> PagoCuotaAsync(string sBank, string sPass, string @__oPago) {
            DistributedServices.Cobranzas_Bancarias_API_Davivienda_ServiceReference.PagoCuotaRequest inValue = new DistributedServices.Cobranzas_Bancarias_API_Davivienda_ServiceReference.PagoCuotaRequest();
            inValue.Body = new DistributedServices.Cobranzas_Bancarias_API_Davivienda_ServiceReference.PagoCuotaRequestBody();
            inValue.Body.sBank = sBank;
            inValue.Body.sPass = sPass;
            inValue.Body.@__oPago = @__oPago;
            return ((DistributedServices.Cobranzas_Bancarias_API_Davivienda_ServiceReference.Cobranzas_Bancarias_API_DaviviendaSoap)(this)).PagoCuotaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DistributedServices.Cobranzas_Bancarias_API_Davivienda_ServiceReference.ReversarPagoResponse DistributedServices.Cobranzas_Bancarias_API_Davivienda_ServiceReference.Cobranzas_Bancarias_API_DaviviendaSoap.ReversarPago(DistributedServices.Cobranzas_Bancarias_API_Davivienda_ServiceReference.ReversarPagoRequest request) {
            return base.Channel.ReversarPago(request);
        }
        
        public DistributedServices.Cobranzas_Bancarias_API_Davivienda_ServiceReference.Saldos ReversarPago(string sBank, string sPass, string @__oPago) {
            DistributedServices.Cobranzas_Bancarias_API_Davivienda_ServiceReference.ReversarPagoRequest inValue = new DistributedServices.Cobranzas_Bancarias_API_Davivienda_ServiceReference.ReversarPagoRequest();
            inValue.Body = new DistributedServices.Cobranzas_Bancarias_API_Davivienda_ServiceReference.ReversarPagoRequestBody();
            inValue.Body.sBank = sBank;
            inValue.Body.sPass = sPass;
            inValue.Body.@__oPago = @__oPago;
            DistributedServices.Cobranzas_Bancarias_API_Davivienda_ServiceReference.ReversarPagoResponse retVal = ((DistributedServices.Cobranzas_Bancarias_API_Davivienda_ServiceReference.Cobranzas_Bancarias_API_DaviviendaSoap)(this)).ReversarPago(inValue);
            return retVal.Body.ReversarPagoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DistributedServices.Cobranzas_Bancarias_API_Davivienda_ServiceReference.ReversarPagoResponse> DistributedServices.Cobranzas_Bancarias_API_Davivienda_ServiceReference.Cobranzas_Bancarias_API_DaviviendaSoap.ReversarPagoAsync(DistributedServices.Cobranzas_Bancarias_API_Davivienda_ServiceReference.ReversarPagoRequest request) {
            return base.Channel.ReversarPagoAsync(request);
        }
        
        public System.Threading.Tasks.Task<DistributedServices.Cobranzas_Bancarias_API_Davivienda_ServiceReference.ReversarPagoResponse> ReversarPagoAsync(string sBank, string sPass, string @__oPago) {
            DistributedServices.Cobranzas_Bancarias_API_Davivienda_ServiceReference.ReversarPagoRequest inValue = new DistributedServices.Cobranzas_Bancarias_API_Davivienda_ServiceReference.ReversarPagoRequest();
            inValue.Body = new DistributedServices.Cobranzas_Bancarias_API_Davivienda_ServiceReference.ReversarPagoRequestBody();
            inValue.Body.sBank = sBank;
            inValue.Body.sPass = sPass;
            inValue.Body.@__oPago = @__oPago;
            return ((DistributedServices.Cobranzas_Bancarias_API_Davivienda_ServiceReference.Cobranzas_Bancarias_API_DaviviendaSoap)(this)).ReversarPagoAsync(inValue);
        }
    }
}
